Controllers films users
Fyodor-Mityanin/java-filmorate pull request #1
Opened 2022-10-04 08:31 UTC by Fyodor-Mityanin

9 спринт

2022-10-05 18:31 UTC, alexache requested changes

2022-10-05 18:31 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private final List<Film> films = new ArrayList<>();
Не самая лучшая структура для хранения инфомрации такого рода. В случае поиска по айди приходится перебирать весь список, что не хорошо. Тут лучше бы подошла мапа

2022-10-05 18:31 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    private final List<User> users = new ArrayList<>();
Здесь такой же комментарий про структуру хранения

2022-10-05 18:31 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +    void createFailDate() {
Мало тестов, по ТЗ необходимы тесты на все граничные условия

2022-10-05 18:31 UTC, alexache commented on src/test/java/ru/yandex/practicum/filmorate/controllers/UserControllerTest.java
> +    void putWithoutId() {
Здесь тоже мало тестов

2022-10-09 08:23 UTC, Fyodor-Mityanin commented
добавил тестов

2022-10-10 11:46 UTC, alexache approved these changes

2022-10-10 14:47 UTC, merged