Add database
Fyodor-Mityanin/java-filmorate pull request #3
Opened 2022-11-14 18:25 UTC by Fyodor-Mityanin

2022-11-15 23:48 UTC, alexache requested changes

2022-11-15 23:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        Optional<User> newUser = getUserById(id);
Будет вполне достаточно выставить полученный id объекте user без дополнительного запроса к базе

2022-11-15 23:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public Optional<User> getUserById(Long id) {
Этот класс уже не обязательно поддерживать

2022-11-15 23:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +    public MpaDbStorage(JdbcTemplate jdbcTemplate) {
@Autowired

2022-11-15 23:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                .map(i -> Genre.builder().id(Long.valueOf(i)).name(getGenreName(Long.parseLong(i))).build())
Выглядит не очень оптимально. К чему делать такие манипуляции с жанрами. чтобы потом их получать так сложно? Отчего бы не сделать 1 просто запрос на получение всех жанров по айди фильма?
Но в случае получения всего списка фильмов это тоже нужно сделать всего 1 запросом, то есть лучше не делать это в данном общем методе

2022-11-15 23:48 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                .name(getMpaName(rs.getLong("MPA")))
Это можно получать первым же запросом фильма (фильмов) с использованием джоина, чем написанием отдельного запроса

2022-11-16 11:37 UTC, Fyodor-Mityanin commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +    public Optional<User> getUserById(Long id) {
Тут пришлось, сигнатура интерфейса поменялась

2022-11-16 23:14 UTC, alexache requested changes

2022-11-16 23:14 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        genreStorage.getAll().forEach(g -> genreCache.put(g.getId(), g));
Немного специфичное решение проблемы. Если появляется кеширование, то появляется проблема поддержки консистентности данных, это выходит за рамки курса. 
Есть более простое решение проблемы лишних вызовов - для MPA использовать запрос фильмов с джоином на таблицу MPA, а для жанровзапрос жанров для фильма/списка фильмов из сервиса

2022-11-18 13:27 UTC, alexache approved these changes

2022-11-18 13:27 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                     "       group_concat(concat(G.ID, ':', G.NAME) separator ',') AS GENRE\n" +
Это все равно еще выглядит довольно костыльно. Так что если в последующих итерациях будут проблемы с рефакторингом этого, то лучше перейти на более классическое решение проблемы

2022-11-20 15:22 UTC, merged